# Generated by Django 5.1.2 on 2024-10-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expertise_des',
            field=models.TextField(blank=True),
        ),
    ]
