# Generated by Django 5.1.2 on 2024-10-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_about_descripion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='descripion',
            new_name='description',
        ),
    ]
