# Generated by Django 5.1.2 on 2024-11-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_about_profile_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
