# Generated by Django 5.1.2 on 2024-11-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
